name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 15.4
        run: sudo xcode-select -s "/Applications/Xcode_15.4.app/Contents/Developer"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List schemes
        run: xcodebuild -list -project StakeOnYou.xcodeproj | cat

      - name: Build (Simulator)
        run: |
          xcodebuild \
            -project StakeOnYou.xcodeproj \
            -scheme StakeOnYou \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=16.4' \
            -configuration Debug \
            build | xcpretty
        env:
          NSUnbufferedIO: "YES"

      - name: Test (Simulator)
        run: |
          xcodebuild \
            -project StakeOnYou.xcodeproj \
            -scheme StakeOnYou \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=16.4' \
            -configuration Debug \
            test | xcpretty
        env:
          NSUnbufferedIO: "YES"


