name: iOS CI (Simulator + Archive)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_PATH: StakeOnYou.xcodeproj
  WORKSPACE_PATH: StakeOnYou.xcworkspace
  SCHEME: StakeOnYou
  SIM_DEVICE: "iPhone 15"
  CONFIG: Debug

jobs:
  build-test-archive:
    runs-on: macos-14

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Select Xcode version
      - name: Select Xcode 15.4
        run: sudo xcode-select -s "/Applications/Xcode_15.4.app/Contents/Developer"

      - name: Show Xcode version
        run: xcodebuild -version

      # 3️⃣ Install xcpretty for readable logs
      - name: Install xcpretty
        run: gem install xcpretty --no-document

      # 4️⃣ Resolve Swift Packages
      - name: Resolve Swift Packages
        run: |
          if [ -f "$WORKSPACE_PATH" ]; then
            xcodebuild -resolvePackageDependencies -workspace "$WORKSPACE_PATH"
          else
            xcodebuild -resolvePackageDependencies -project "$PROJECT_PATH"
          fi

      # 5️⃣ Build on Simulator
      - name: Build (Simulator)
        run: |
          if [ -f "$WORKSPACE_PATH" ]; then
            xcodebuild \
              -workspace "$WORKSPACE_PATH" \
              -scheme "$SCHEME" \
              -destination "platform=iOS Simulator,name=${SIM_DEVICE}" \
              -configuration "$CONFIG" \
              build | xcpretty
          else
            xcodebuild \
              -project "$PROJECT_PATH" \
              -scheme "$SCHEME" \
              -destination "platform=iOS Simulator,name=${SIM_DEVICE}" \
              -configuration "$CONFIG" \
              build | xcpretty
        env:
          NSUnbufferedIO: "YES"

      # 6️⃣ Run tests on Simulator
      - name: Test (Simulator)
        run: |
          if [ -f "$WORKSPACE_PATH" ]; then
            xcodebuild \
              -workspace "$WORKSPACE_PATH" \
              -scheme "$SCHEME" \
              -destination "platform=iOS Simulator,name=${SIM_DEVICE}" \
              -configuration "$CONFIG" \
              test | xcpretty
          else
            xcodebuild \
              -project "$PROJECT_PATH" \
              -scheme "$SCHEME" \
              -destination "platform=iOS Simulator,name=${SIM_DEVICE}" \
              -configuration "$CONFIG" \
              test | xcpretty
        env:
          NSUnbufferedIO: "YES"

      # 7️⃣ Archive for generic iOS device (unsigned)
      - name: Archive (Generic iOS Device)
        run: |
          if [ -f "$WORKSPACE_PATH" ]; then
            xcodebuild \
              -workspace "$WORKSPACE_PATH" \
              -scheme "$SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              archive \
              -archivePath "$RUNNER_TEMP/StakeOnYou.xcarchive" | xcpretty
          else
            xcodebuild \
              -project "$PROJECT_PATH" \
              -scheme "$SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              archive \
              -archivePath "$RUNNER_TEMP/StakeOnYou.xcarchive" | xcpretty

      # 8️⃣ Upload archive artifact (always)
      - name: Upload xcarchive artifact
        uses: actions/upload-artifact@v4
        with:
          name: StakeOnYou-archive
          path: ${{ runner.temp }}/StakeOnYou.xcarchive
